### ISSUE TITLE
Kanban panel is "under" the editor panel when positioned together in layout

### ISSUE THREAD

**Issue by TDMedina** [joplin/plugin-kanban#25]
I have my Kanban board positioned in the center, below the editor pane, as shown:
![image](https://user-images.githubusercontent.com/32261345/156031819-acf76087-d1d1-4b6e-8c6e-1c61944320d5.png)

When I adjust the height of the Kanban board and move it up, it ends up underneath text from the editor panel:
![image](https://user-images.githubusercontent.com/32261345/156032226-c17b482d-c001-494c-a456-6698ec32ec7e.png)

![image](https://user-images.githubusercontent.com/32261345/156032425-5dbc9c14-2ffb-4c69-a161-97f717f8b0f8.png)

Preferably the Kanban panel would just cover the editor panel.

**Comment by mablin7** [comment]
Does anything like this happen with other plugins?

**Comment by TDMedina** [comment]
Good question! I just checked, and yes, my outline plugin does the same thing if moved to the center pane. Is this a Joplin bug then? Or just a me problem?

**Comment by mablin7** [comment]
Probably the first. Please make a bug report on the Joplin repo.
