### ISSUE TITLE
YAML Parse error

### ISSUE THREAD

**Issue by Bug23451** [joplin/plugin-kanban#43]
Plugin non functional and references a YAML error on Joplin.

Only tested on the linux appimage (2.9.17) and the Flatpack (2.9.17).

![2023-05-08-121936_hyprshot](https://user-images.githubusercontent.com/38907238/236719498-ba1e32fc-58d8-44b0-a41b-a0459ea7dc90.png)

**Comment by Zszywek** [comment]
Same thing for me after installing with a script on Ubuntu

**Comment by anicholslcsw65** [comment]
Same thing here.  Any suggestions?

**Comment by derkrasseleo** [comment]
I get the same message, but without the reason on Windows 11

**Comment by benlau** [comment]
Could anyone share your kanban config with error here?

**Comment by derkrasseleo** [comment]
this works:

```
columns:
- name: Backlog
backlog: true
```
as soon as I add a second `name` tag, it fails

```
columns:
- name: Backlog
backlog: true
- name: wip
tag: wip
```

**Comment by derkrasseleo** [comment]
I think it has something to do with tabs vs. spaces, because if I paste the default config from the readme, I get no such error.

**Comment by benlau** [comment]
@derkrasseleo 2 Spaces before backlog and tag are required for YAML format (Tab are not allowed). This config should works

```kanban
columns:
- name: Backlog
  backlog: true
- name: wip
  tag: wip
```

**Comment by Zszywek** [comment]
It may be useful for some people as it worked for me to leave the language field simply blank

**Comment by derkrasseleo** [comment]
Just wanted to add: I solved the Parse error by using spaces instead of tabs
