### ISSUE TITLE
Feature request: change scale

### ISSUE THREAD

**Issue by OmnixPL** [joplin/plugin-kanban#5]
Could you please add an option to change the scale of the board? Font size is much larger than anything else in the app by a big margin. On 1920x1080 fullscreen it takes up more space than note view itself and in windowed it makes rest of the application unusable. The board gets scaled when Joplin is scaled using ctrl + + / ctrl + -, but when the board is at comfortable size, the rest of the app is very hard to read.

**Comment by mablin7** [comment]
Hey! Check out the new release, I changed the scale of many elements, and the font size now depends on Joplin's editor font size. Let me know what you think!
