### ISSUE TITLE
Can't add any card to the board

### ISSUE THREAD

**Issue by theCollectiv** [joplin/plugin-kanban#6]
I can't add any card to the board.
I tried the `+` Button for each column of the kanban board. It opens a new note, which I did edit. But afterwards is no change to the kanban board. The note exists in the joplin-note-list; but there is no way to get it on the kanban board/convert it into a kanban-card.
I also added a note to the kanban notebook and tried to get it to the board without success.
Am I missing something to get it work?

***

The kanban config is
```kanban
columns:
  - name: Backlog
    backlog: true
  - name: Work in progress
    tag: wip
  - name: Finished
    tag: done
  - name: Additional Info
```
I use Joplin 2.4.9 and installed the plugin via Joplin (kanban V1.0.4.).
![2021-10-28_10-26_kanban](https://user-images.githubusercontent.com/78902012/139223684-f513c2da-eac7-4e5a-9f9b-c81f934cd6b3.png)

*** 
There is another ...strange behaviour; everytime I leave the notebook/folder, which is including the kanban-config and re-enter the notebook/folder, a copy of the parent directory with just including the kanban-notebook/folder (no notes in there) is made.

![2021-10-28_10-55_kanban](https://user-images.githubusercontent.com/78902012/139223730-29934fa9-04b4-49ed-9c08-745c4b5361a1.png)
0-a0ef1bb7-4963-4d5f-bb8d-ebad41a60f75.png)

**Comment by mablin7** [comment]
Something broke with the latest joplin release, I'll check it as soon as I can

**Comment by theCollectiv** [comment]
If u want to have someone to test it then, just tell me, when its ready to test.

**Comment by mikestaub** [comment]
I tested on Joplin@2.5.12 and it works

**Comment by shinglyu** [comment]
Tested on both v2.3.3 and v2.5.12 and it's still broken. However, the kanban board I created a few weeks ago seems to work fine. But any new one is broken.

**Comment by shinglyu** [comment]
@mablin7 I found the problem. `joplin.data.get(["folders"])` is paginated, so if the user has more than 100 (default pate limit) folders, the `resolveNotebookPath` might not find the folder and decide to create one. ~I don't have time today but I'll try to fix it some other day~.

There are more `joplin.data.get()` calls that forget to do pagination, so we might need to fix those as well.

**Comment by shinglyu** [comment]
It's an easier fix than I thought, should be fixed by #9

**Comment by shinglyu** [comment]
@mablin7 do you mind if I release the new version for you? Because I really want to get this fix using the official channel. If I understand it correctly I should open a PR to https://github.com/joplin/plugins repo with the updated `.jpl` file and update the version in the README? I can create an SHA-1 hash of the `.jpl` file so you can verify the package? (Not sure if the compiler and dependency will cause the package to be slightly different...)

**Comment by mablin7** [comment]
Oh no, it doesn't work like that, I have to release through npm. But I'll do it right now

**Comment by mablin7** [comment]
There, the update should show up in an hour or so.

**Comment by shinglyu** [comment]
Just received the update! Thank you so much!
