### ISSUE TITLE
Switching between two different boards does not auto-refresh

### ISSUE THREAD

**Issue by chk86** [joplin/plugin-kanban#7]
I've created two different kanban boards and noted that when I switch between the two boards which are located in two different notebooks, the one I switch to still shows the tasks from the previous board. If I manually update the YAML code, it will immediately refresh and show the new board's items. But that's the only way I've figured out how to refresh the boards.

**Comment by chk86** [comment]
I was trying it again today and for whatever reason, it seems to be working perfectly today.

**Comment by Ziron** [comment]
I have this same problem so it still seems to be an issue.
